<a href="https://colab.research.google.com/github/jlvoltan/bootcamp_python/blob/master/m2_cap1e2_boot_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Módulo 2 - Cap 1,2 - Bootcamp PYTHON**
*Atualizado em 27 JUL 2020* 

*jlvoltan*

**Etapas da Análise de dados:**
 1. Definição do Problema a ser trabalhado
 2. Coleta de dados
 3. Tratamento de dados
 4. Análise de dados
 5. Visualização


## **Numpy**


* Biblioteca de computação científica;
* Boa performance (melhor que Python puro);
* usacdo com o apelido np
* Focada em trabalhar com os arrays e manipulação de números

 * Vetor = 1 Dimensão
 * Matriz = 2 Dimensão 
* ***axis*** representa a direção da dimensão
* ***shape*** quantidade de elementos por linha, coluna...

* Instalação
 1. pip install numpy
 2. conda install numpy

In [1]:
import numpy as np

In [2]:
#Podemos ver o help com exemplos...
#help(np.array)

## Vetor - 1 dim

* Indice dos vetores: 0 a n-1
* Pode-se usar indices negativos: -1 equivale ao último elemento

In [3]:
linha = [1,2,1]
print(type(linha))

x = np.array(linha)  
#Posso ainda forçar o tipo de dado:
#       x = np.array(linha, dtype=int)  
print(type(x))
print("Vetor: " + str(x)+" com Shape: "+ str(x.shape))

<class 'list'>
<class 'numpy.ndarray'>
Vetor: [1 2 1] com Shape: (3,)


In [4]:
linha[1]

2

## Matriz

In [5]:
linha1 = ['a',2,1]
linha2 = [1,3,1]
Matriz= [linha1,linha2]
# ou direto Matriz= [[1,2,1], [1,3,1]]
x = np.array(Matriz)

print("Vetor: " + str(x)+"                 com Shape: "+ str(x.shape))

Vetor: [['a' '2' '1']
 ['1' '3' '1']]                 com Shape: (2, 3)


In [6]:
Matriz[1][1]

3

* **reshape** : Alterar a forma de um array (remodelar)
 * reshape(-1,1): ignoro a quantidade de linhas, mas imponho que senha um vetor coluna.


In [7]:
x = [1,2,3,4,5,6,7,8,9,10]
Array = np.array(x)  
print(Array)
print()
print(Array.reshape(2,5))
print()
print(Array.reshape(5,2))

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## Funções para criar arrays preenchidos

* Criar array de 0's (zeros):
  * np.zeros(dimensoes)

In [8]:
  print(np.zeros((2,2)))
  print(np.zeros(5))
  print(np.zeros(5,dtype=int))

[[0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]


* Criar array de 1's (um):
  * np.ones(dimensoes)

In [9]:
  print(np.ones((2,2)))
  print(np.ones(5))
  print(np.ones(5,dtype=int))

[[1. 1.]
 [1. 1.]]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


* Criar array Linerarmente espaçado:
  * np.linspace(strart=  ,stop=  ,numero_de_elementos)


In [10]:
x = np.linspace(0,30,3)
print("Vetor: " + str(x)+" com Shape: "+ str(x.shape))

Vetor: [ 0. 15. 30.] com Shape: (3,)


* Criar Matriz identidade:
 * É aquela matriz quadrada com apenas a diagonal principal com 1.
  * np.eye(dimensao)

In [11]:
x = np.eye(3)
print("M=" + str(x)+"          com Shape: "+ str(x.shape))

M=[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]          com Shape: (3, 3)


* Array de números aleatórios
 * Valores uniformemente distribuidos no intervalo 0 e 1



In [12]:
x = np.random.random(size=(3,3))
print("M=" + str(x)+"          com Shape: "+ str(x.shape))

M=[[0.99297735 0.34691253 0.26008787]
 [0.91072011 0.76045298 0.76427442]
 [0.688389   0.65134536 0.24141047]]          com Shape: (3, 3)


In [13]:
np.random.seed?

## Fatiar (To SLICE)
 * vetor[ inicio : fim ] == >pegaria de inicio até fim-1
 * vetor[ inicio : fim : passo] == >pegaria de inicio até fim-1, pulando elementos.
 - perceba que o **fim é exclusive** (não entra)
 * O Fatiamento faz na verdade um **compartilhamento de memória** e não uma cópia; se altero o elemento fatiado tem reflexo no original.

In [14]:
linha = [0,1,2,3,4,5,6,7]
linha1 = np.array(linha)  

#Imprimindo os indices pares 
print(linha1[0:len(linha1):2])

#Criei um elemento com base no array linha1
a = linha1[2:5]
#alterei um de seus elementos, com reflexo em linha1
a[0]=9

print(linha1)

[0 2 4 6]
[0 1 9 3 4 5 6 7]


In [15]:
linha0 = [1,2,1]
linha1 = [1,3,1]
linha2= [9,8,7]
Matriz= [linha0,linha1,linha2]
Array_2D = np.array(Matriz) 

print(Array_2D[1:3,0:1])

[[1]
 [9]]


### Fatiar (To SLICE) COM CÓPIA

In [16]:
linha = [0,1,2,3,4,5,6,7]
linha1 = np.array(linha)  

#Criei um elemento com base no array linha1
a = linha1[2:5].copy()
#alterei um de seus elementos, com reflexo em linha1
a[0]=9
print(a)
print(linha1)

[9 3 4]
[0 1 2 3 4 5 6 7]


## Operações básicas
* São feitas elemento a elemento;
* elementos (arrays) devem ser de igual dimensão

 * SOMA: + ou *np.add*
 * SUBTRAÇÃO: - ou *np.subtract*
 * MULTIPLICAÇÃO: * ou *np.multiply* 
   * NÃO confundir com multiplicação vetorial
 * DIVISÃO: / ou *np.divide*

In [17]:
x = [1,2,3,4,5,6,7,8,9,10]
x = np.array(x)  
y = np.ones(10)

In [18]:
#z = x + y
z1 = np.add(x,y)
print ("z1: \n",z1)

z1: 
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [19]:
#z2 = x - y
z2 = np.subtract(x,y)
print ("z2: \n",z2)

z2: 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [20]:
z3 = x * (2*y)
#z3 = np.multiply(x,y)
print ("z3: \n",z3)

z3: 
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [21]:
z4 = x / (2*y)
#z4 = np.divide(x,y)
print ("z4: \n",z4)

z4: 
 [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


## BROADCASTING: 
* Propaga a operação por todos elementos
* pode ser útil para arrays grandes e com simetria.
* Não funciona sempre. P.e. Não dá pra querer usar com um array de dimensão 2 e outro 5

In [22]:
x = [1,2,3,4,5,6,7,8,9,10]
x = np.array(x)
# Ao inves de ter [5 5 5 5 5 5 5 5 5 5]     fiz apenas [5]
y=[5]  
y = np.array(y)

In [23]:
#z = x + y
z1 = np.add(x,y)
#Mas o resultado foi o mesmo de y = [5 5 5 5 5 5 5 5 5 5]
print ("z1:\n",z1)

z1:
 [ 6  7  8  9 10 11 12 13 14 15]


In [24]:
z2 = x + 5
print("z2:\n",z2)

z2:
 [ 6  7  8  9 10 11 12 13 14 15]


## Multiplicação Matricial
* Numpy: np.dot(x,y) ou x.dot(y)
*Python: x @ y

In [25]:
x = [[1,2],[3,4]]
x = np.array(x)

y = np.ones((2,2))
y = 2*y

In [26]:
#x @ y
c = np.dot(x,y)
print(" x @ y : \n", c)

 x @ y : 
 [[ 6.  6.]
 [14. 14.]]


## Solução de sistemas lineares

* Por exemplo:
 * x + y = 8
 * 2x - y = -2

 * Monto o produto de Matrizes A * B = C
  Multiplico à esquerda pela inversa de A, lembrando que uma matriz vezes a sua inversa gera a matriz identidade 

```
B = inv(A)*C
```



In [27]:
A = np.array([[1,1],[2,-1]])
C = np.array([[8],[-2]])
print("A: \n", A)
print("C: \n", C)

A: 
 [[ 1  1]
 [ 2 -1]]
C: 
 [[ 8]
 [-2]]


In [28]:
#Solução 1
B = np.dot(np.linalg.inv(A),C) 
print("Solução B: \n", B)

Solução B: 
 [[2.]
 [6.]]


In [29]:
#Solução 2
B = np.linalg.inv(A) @ C 
print("Solução B: \n", B)

Solução B: 
 [[2.]
 [6.]]


## Comparações entre Arrays
* Elemento a elemento; ou
* Broadcast


```
* > < <= >= ==   !=
```





In [30]:
A = np.array([7,8])
#A = np.array([7,8,9,10])
B = np.array([[6,18],[10,5]])
#B = np.array([6,18,10,5])
C = np.array([1])
D=8
print("A>B: ", A>B)
print("A>C", C==A)
print("A>8", A>D)

A>B:  [[ True False]
 [False  True]]
A>C [False False]
A>8 [False False]


## Indexação Booleana
* traço uma condição lógica para um array, pego dele, só as posições em que a condição é True
* Funciona uma espécie de filtro, onde extraio só os valores que tornam a condição verdadeira

```
Condição = array_velho condição
novo_array = array_velho[Condição]
```
```
Onde, condição:    > < <= >= ==   != 
```

In [31]:
A = np.array([7,8,8,10])
condicao = A != 8
B = A[condicao]
print("B: \n", B)

B: 
 [ 7 10]


## Outras Operações

In [32]:
A = np.array([1,2,3,4,5,6,7,8])
A2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

### RESHAPE

In [33]:
B = A.reshape(2,4)
print("B: \n", B)

B: 
 [[1 2 3 4]
 [5 6 7 8]]


### Matriz Transpostas
* Cuidado pois a matriz linha **não** vira matriz coluna (difere da definição clássica de transposição, mas pra matriz quadrada dá certo)

In [34]:
B = A2.T
print("B: \n", B)

B: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [35]:
#Entendendo mais com o HELP
A.T?

### Função soma (sum)
* Dois formas de se chamas *array.sum()* ou *np.sum(array)*
* Opções de Soma:
 
 1. Somar todos elementos;
 2. Somar em cada eixo (linhas ou colunas) 

In [36]:
print(A.sum())
print(np.sum(A2))

36
45


In [37]:
#Axis=0, "juntou todas linhas em uma só"
print("axis=0 : \n", A2.sum(axis=0))
#Axis=1, "juntou todas colunas em uma só"
print("axis=1 : \n",np.sum(A2,axis=1))

axis=0 : 
 [12 15 18]
axis=1 : 
 [ 6 15 24]


### Função média (mean)
* Dois formas de se chamas *array.mean()* ou *np.mean(array)*
* Opções de Soma:
 
 1. Média de todos elementos;
 2. Média em cada eixo (linhas ou colunas) 

* Outras funções similares, mediana (median)

In [38]:
print(A.mean())
print(np.mean(A2))

4.5
5.0


In [39]:
#Axis=0, "juntou todas linhas em uma só"
print("axis=0 : \n", A2.mean(axis=0))
#Axis=1, "juntou todas colunas em uma só"
print("axis=1 : \n",np.mean(A2,axis=1))

axis=0 : 
 [4. 5. 6.]
axis=1 : 
 [2. 5. 8.]


### Localizar (Where)
* retorna a tupla onde a condição é atendida

In [40]:
A2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
condicao = A2> 4
i,j = np.where(condicao)
print("indices linha: \n", i)
print("indices coluna: \n", j)

indices linha: 
 [1 1 2 2 2]
indices coluna: 
 [1 2 0 1 2]
